import { supabase } from '../supabaseClient';
import { roundQty } from '../utils/inventory';

// Kitchen Workflow Integration: the prep list is generated by the database
// function get_kitchen_prep_list(booking_id) from the booking's package,
// the dishes the client picked, and each dish's ingredients x guest count.
// Nothing is stored for the list itself, so it is always in sync with the
// booking. Only the chef's "done" ticks are saved (tbl_prep_checks).

// task_key format is enforced by a CHECK constraint on tbl_prep_checks:
//   dish:<menu item id>        -> a dish that has been prepared
//   ing:<inventory item id>    -> an ingredient that has been pulled/ready
export const dishKey = (itemId) => `dish:${itemId}`;
export const ingKey = (itemId) => `ing:${itemId}`;

export async function getKitchenPrepList(bookingId) {
  const { data, error } = await supabase.rpc('get_kitchen_prep_list', {
    p_booking_id: Number(bookingId),
  });

  if (error) {
    if (error.code === 'PGRST202' || error.code === '42883') {
      throw new Error('Kitchen prep list is not set up in the database yet.');
    }
    if (error.code === '42501') throw new Error('You do not have permission to view the kitchen prep list.');
    throw new Error(error.message || 'Failed to load the kitchen prep list.');
  }

  const checks = {};
  for (const c of data?.checks || []) checks[c.task_key] = c.done_at;

  return {
    booking: data.booking,
    stockReserved: !!data.stock_reserved,
    dishes: data.dishes || [],
    packageIngredients: data.package_ingredients || [],
    totals: data.totals || [],
    checks, // { 'dish:12': '2027-...', 'ing:5': '...' }
  };
}

// Tick / untick one task. The row's done_by / done_at are set by a DB trigger.
export async function setPrepTaskDone(bookingId, taskKey, done) {
  if (done) {
    const { error } = await supabase
      .from('tbl_prep_checks')
      .insert({ booking_id: Number(bookingId), task_key: taskKey });
    // 23505 = already ticked (e.g. by another chef) - that is fine.
    if (error && error.code !== '23505') throw new Error('Failed to save. Please try again.');
  } else {
    const { error } = await supabase
      .from('tbl_prep_checks')
      .delete()
      .eq('booking_id', Number(bookingId))
      .eq('task_key', taskKey);
    if (error) throw new Error('Failed to save. Please try again.');
  }
}

// Kitchen-friendly amount: 0.64 kg -> "640 g", 0.25 L -> "250 mL".
// Everything else keeps its own unit ("12 kg", "80 pcs").
export function formatPrepQty(value, unit) {
  const n = Number(value) || 0;
  if (unit === 'kg' && n > 0 && n < 1) return `${roundQty(n * 1000)} g`;
  if (unit === 'L' && n > 0 && n < 1) return `${roundQty(n * 1000)} mL`;
  return `${roundQty(n)} ${unit || ''}`.trim();
}

// Group the dish list by menu category, in the order the kitchen cooks them.
export function groupDishesByCategory(dishes) {
  const order = ['Main Course', 'Side Dish', 'Dessert', 'Drinks'];
  const groups = {};
  for (const d of dishes) {
    (groups[d.category] ||= []).push(d);
  }
  return order.filter((c) => groups[c]).map((c) => ({ category: c, dishes: groups[c] }));
}